### ISSUE TITLE
部分行号不显示

### ISSUE THREAD

**Issue by qLzhu** [Eleven90/gitbook-plugin-code-optimize#1]
在引入 JavaScript 内容时，script 标签部分行号显示不完整

<img width="467" alt="截屏2020-05-23 下午2 13 41" src="https://user-images.githubusercontent.com/16423359/82723209-b7a72700-9cff-11ea-9769-1d18309e673a.png">

**Comment by Eleven90** [comment]
> 在引入 JavaScript 内容时，script 标签部分行号显示不完整
> 
> <img alt="截屏2020-05-23 下午2 13 41" width="467" src="https://user-images.githubusercontent.com/16423359/82723209-b7a72700-9cff-11ea-9769-1d18309e673a.png">

此类问题暂时没有好办法，我已经放弃 gitbook 了，推荐你 使用 docsify
